In [2]:
import sys
import numpy as np

In [13]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
print(a)
print(b)
a+b
c = np.array([5,7,4,5], dtype=float)
c

[1 2 3 4]
[5 6 7 8]


array([5., 7., 4., 5.])

In [8]:
b

array([5, 6, 7, 8])

Dimension and shapes

In [14]:
a = np.array([
    [1,2,3],
    [3,9,0],
    [2,5,6]
])

In [15]:
a

array([[1, 2, 3],
       [3, 9, 0],
       [2, 5, 6]])

In [17]:
a.size


2

In [18]:
a.ndim

2

In [19]:
a.shape

(3, 3)

indexing and slicing 

In [20]:
a = np.array([
    [1,4,6,78,8],
    [56,34,2,6,8],
    [3,34,556,23,45],
    [123,32,1,56,7],
    [1,6,78,90,980]
])

In [21]:
a

array([[  1,   4,   6,  78,   8],
       [ 56,  34,   2,   6,   8],
       [  3,  34, 556,  23,  45],
       [123,  32,   1,  56,   7],
       [  1,   6,  78,  90, 980]])

In [22]:
a.shape

(5, 5)

In [24]:
a[0,3]

np.int64(78)

In [25]:
a[2,2]

np.int64(556)

In [26]:
a[2,2] + a[1,2]

np.int64(558)

In [27]:
a[:, 2]

array([  6,   2, 556,   1,  78])

In [30]:
a[4] = 8000
a[:, 4] = 9000

In [31]:
a

array([[   1,    4,    6,   78, 9000],
       [  56,   34,    2,    6, 9000],
       [   3,   34,  556,   23, 9000],
       [ 123,   32,    1,   56, 9000],
       [8000, 8000, 8000, 8000, 9000]])

summury statistics

In [33]:
n = np.array([
    [1,4,6,78,8],
    [67,34,2,6,8],
    [3,34,556,23,45],
    [123,32,1,56,7],
    [1,6,78,90,980]
])

In [34]:
n

array([[  1,   4,   6,  78,   8],
       [ 67,  34,   2,   6,   8],
       [  3,  34, 556,  23,  45],
       [123,  32,   1,  56,   7],
       [  1,   6,  78,  90, 980]])

In [36]:
n.mean()

np.float64(89.96)

In [35]:
n.var

<function ndarray.var>

In [37]:
n.std()

np.float64(211.3239181919548)

In [38]:
n[1].mean()

np.float64(23.4)

Broadcating and vectorized operations

In [39]:
a = np.arange(4)

In [40]:
a

array([0, 1, 2, 3])

In [41]:
a +10

array([10, 11, 12, 13])

In [43]:
[i*2 for i in a]

[np.int64(0), np.int64(2), np.int64(4), np.int64(6)]

In [47]:
b = np.array([10,10,10, 30])
b

array([10, 10, 10, 30])

In [48]:
a+b

array([10, 11, 12, 33])

In [2]:
import numpy as np

mat = np.array([
    [3,5,6],
    [56,7,8],
    [55,78,90]
])

In [3]:
mat

array([[ 3,  5,  6],
       [56,  7,  8],
       [55, 78, 90]])

boolean arrays

In [4]:
import numpy as np

In [7]:
a = np.arange(6)

In [8]:
a

array([0, 1, 2, 3, 4, 5])

In [9]:
a[[0, -1]]

array([0, 5])

In [11]:
a>=2

array([False, False,  True,  True,  True,  True])

In [12]:
a[a>=2]

array([2, 3, 4, 5])

In [18]:
# mean

a.mean()


np.float64(2.5)

In [17]:
a[a>a.mean()]

array([3, 4, 5])

Linear algebra

In [19]:
import numpy as np

In [20]:
A = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [22]:
B = np.array([
    [2,3],
    [5,6],
    [2,1]
])

In [27]:
A.dot(B)

array([[18, 18],
       [45, 48],
       [72, 78]])

In [28]:
A@B

array([[18, 18],
       [45, 48],
       [72, 78]])

In [29]:
B.T

array([[2, 5, 2],
       [3, 6, 1]])

In [30]:
B.T@A

array([[36, 45, 54],
       [34, 44, 54]])

Size of objects in memory

Int,floats

In [37]:
import numpy as np

# an integer in python is > 24 bytes
sys.getsizeof(1)

28

In [39]:
# longs are even larger
sys.getsizeof(10**100)

72

useful numpy functions

random

In [46]:
np.random.random(size=2)
np.random.normal(size=2)
np.random.rand(2 ,4)

array([[0.75349953, 0.36658609, 0.18299294, 0.05732391],
       [0.67601805, 0.89531394, 0.73137699, 0.24340547]])

arange

In [51]:
l = list(range(30000))


In [52]:
a = np.arange(30000)


In [53]:
%time np.sum(a**2)


CPU times: total: 0 ns
Wall time: 2.01 ms


np.int64(8999550005000)

In [54]:
%time np.sum([x ** 2 for x in l])

CPU times: total: 15.6 ms
Wall time: 8.31 ms


np.int64(8999550005000)